import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#00210e",
        "surface-container-high": "#e7e8e9",
        "primary-fixed-dim": "#a1d494",
        "secondary-fixed": "#c5eccc",
        "secondary": "#43664d",
        "on-primary-container": "#9dd090",
        "error-container": "#ffdad6",
        "surface-tint": "#3b6934",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#41493f",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "primary-fixed": "#bcf0ae",
        "on-primary-fixed": "#002201",
        "on-primary": "#ffffff",
        "secondary-container": "#c2e9c9",
        "on-secondary-fixed-variant": "#2c4e36",
        "tertiary-container": "#4a5248",
        "surface-container-lowest": "#ffffff",
        "outline": "#72796e",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "primary-container": "#2d5a27",
        "tertiary-fixed-dim": "#c1c9bc",
        "surface-container": "#edeeef",
        "on-primary-fixed-variant": "#23501e",
        "on-tertiary-fixed": "#161d15",
        "surface-container-low": "#f3f4f5",
        "tertiary": "#333b32",
        "on-secondary-container": "#486a51",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "on-tertiary-container": "#bdc5b8",
        "tertiary-fixed": "#dde5d8",
        "inverse-primary": "#a1d494",
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#aad0b1",
        "primary": "#154212",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-surface-variant": "#42493e",
        "inverse-on-surface": "#f0f1f2",
        "outline-variant": "#c2c9bb"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "h1": ["Inter"],
        "body-lg": ["Inter"],
        "h3": ["Inter"],
        "h2": ["Inter"],
        "label-caps": ["Inter"],
        "data-display": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "h3": ["20px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500" }],
        "h2": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "data-display": ["28px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
export default config;
